#!/usr/bin/env python3 
# -*- coding: utf-8; fill-column: 100; truncate-lines: t -*-
#
# Copyright (C) 2014,2015 Jochen Küpper <jochen.kuepper@cfel.de>

import anglePDF
import sys


if __name__ == "__main__":
	inputstring = sys.argv[1]



